keywords = "metaphist"
theme = "dark"
primary_color = "rgba(255, 255, 255, 0.1)"
text_align = "center"
base_url = "https://metaphist.github.io"
image = "transparent.png"

[[sections]]
direction = "column"
item_style = "filled"
[[sections.items]]
title = "Notes"
url = "http://notes.metaphist.com"
icon = "https://cdn.simpleicons.org/obsidian"
[[sections.items]]
title = "Vids"
url = "https://www.youtube.com/user/AngrySonMetaphist"
icon = "https://cdn.simpleicons.org/youtube"