name = "metaphist"
description = "Testing 123"
keywords = "metaphist"
image = "jake.webp"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-XLJ81DCZFV"
base_url = "https://metaphist.github.io"

[[sections]]
direction = "column"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/obsidian"
title = "Notes"
url = "http://notes.metaphist.com"
